import type { Metadata } from "next";
import {
  Audiowide,
  Racing_Sans_One,
  Space_Mono,
  Stalinist_One,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const stalinistOne = Stalinist_One({
  variable: "--font-stalinist-one",
  subsets: ["latin"],
  weight: "400",
});

const racingSansOne = Racing_Sans_One({
  variable: "--font-racing-sans-one",
  subsets: ["latin"],
  weight: "400",
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

const audiowide = Audiowide({
  variable: "--font-audiowide",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${stalinistOne.variable} ${racingSansOne.variable} ${spaceMono.variable} ${audiowide.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
